sudo: required
matrix:
  include:
  - services:
    - docker
    env: VARIANTS=default
before_install:
- |
  go get github.com/openshift/source-to-image
  pushd ${GOPATH}/src/github.com/openshift/source-to-image
  export PATH=$PATH:${GOPATH}/src/github.com/openshift/source-to-image/_output/local/bin/linux/amd64/
  hack/build-go.sh
  popd
script:
- if [ "$TRAVIS_BRANCH" = "master" ]; then export DOCKER_PUSH=true && docker login
  -u="$DOCKER_USER" -p="$DOCKER_PASS" quay.io; fi
- "./hack/run build"
notifications:
  slack:
    secure: CYW5oGoaHRilaAaoBGrbMfLLsosdLoPi8gNAIOhw6bYGlj2OS8Nr+wm/QUbwCGrrap4PCCx/dL5TH9YBtSI+xRoST3+NJ6c5XlLsyCsJYnmLpAtFXUxo5XCM77jn2K4KeAg/iMqKvLeOCYzxwJiuIo9GIr+5p2NtBPIR/l5OslvmEdCVLV5T9dKe0TxRIoAAS9j5tz6Z8WAuhGSg+NHMAKpoaR3XkzgHW3zk7B60JxBZrBqYXifF0zzfILP0OlBKj7xk2UCqw7JMb+3ha/OOcplqF6SjUjx2bWUb+lQzEEUhiaeSUAKssq8RfbjQiRCZNJDEd3OnUR+swvgyEA9qei0Yi/Tqd9+Lydz8yLPCWu8gWx6ZIJVnS9yjGyr1QaJNbMoPeeJCVuQfBObfH8TIoQOhBXVNDkyrv4fRGDMEMe+Z3QCidi++uVwgDxVIeH+MBl2hwwGZbX2dzeyP/pOxuqHbGUXUTsv8jDdYgZYWckCWARxS9JwinSoKfLjAvKeDCz87vzrQ6qp9prl3gAvYShmHOP3/AIwT4sfKxu2hB0IW5qs9/oNg4hP5K/plsQ9Q68uS2hf8qv4n2sx+0kSO3dJdZK7mK5u2DrUDeJYU2RgNnm0xtQCpE20fVITzxiV8z2VS9SxJkds6786ArkL5EcFqNrUPXMzH9M5QP8cQGHc=
env:
  global:
  - secure: zjPuYa9T08t3YpkctnKg5ztHFrtdhAgUgEwWvtF7Lt+WJxlQkVJLKJp7F+0UCqTIec3OT1lB0h/XVMsNwh/SknSFy4YVZAuRX5f9AGjDTd9M3JiJ8Eg0QlM6RDnWtve1IgTUf/EnWE/mRKhL71+Et3eSzZquZcxK9qUILr6G/YL+yzymJ7idDEbV4KeMcZ3NFaBbTdEHPFxyPQhL+O69ZQOFuXco2tXJ7eOZ9RteAPDM7UQazD1b0+XRJwEEUmfSAEktSf0alWjwEw0xRGcZ3aGJnRFPmDAqWjtqJRKbFOPNM/fXO7VnXXJeRRXvauWHt8/Hg5Gpza6DOR1Nr9Kc5HLXeMjk3wZKOjtSY/ccyItOluh0aZVQKmKshi50C9oujsJXboeMFOyp+Sk5hDTv5UjS8+fE5YCk+ehUfR/B75FiXVw5fpLJhnNjjRulahs2zsER8IXNjA6J6o5njgTKKqXL6+SoE4jZYnzMvyjWIw9DSytZwwPIps8EbE8vtQ+vu2wYR+2sOEtXhWv71+XP5svo00/UzSUYVgS/ryL2m2MdR/qn17Xj5Bmk1a0uQIbWLKphObUSz6kb8Ani62u6nScXMN4I6+f6sOYvUva8EJje/o5V+TmB+uemPl8M4JrlS35JCo+GlYK5Al9bs7hfwaejpY9I99HXsJp9otCB2pk=
  - secure: RGtoWu1QnLtYKtKaH3b1+gw48hC9Ddjao0ROe7THHDJUOAfM15wryKSQ/CX9Cua6z4z2+0xpVqL/3C8vGLdLrfG/ecS2tk1IBrFp+wrWcP3rxY0DIpQLKEGttJzNKxEh5+USV0DF1BCksCbb89zm7F7SAV8bKQY1+L7NM2ynLCNFOZ9L9EzRvu0saHyxERFf+LSwSOKyBwBa5x+JeaoHHrDV5fqP6Yt4WKuyuPTcvPa90gzgXIOgxW8ZM422PyY6MjdQmXiDrE4SjjfwCZ9qdoqzLBOQd5SJFyDJXGCUnt4wMLJmE2Sq+KgauC8Tm50e1OOv+SxrhX0TPsKk6EbOxHS2nvJaPPEKZncShLFvhS3SuyD2/RV5YDlVgJjJgQQgEVdNOtwpIaaRNr87LLSPJrIUr330kyd8fjZeEeo21QTs7FrrOpfDmEOjEs3nS9Uw07aw9mTV0bXizXToU7Lc3LJLoHk+mQL+4boTvsTDDI9uydoyRp3YpKgnH7w4ED0ma8wBZyTEh43Ks0jbgYEzq6FutzxpNp0jU66DOOMLe0wPW0VbaOPcUmAIgVj5I8SAkUpZ+JAm36X75Obu2E8nzTKojYNskpLSs+mCrKtVOTWb5oqnYcx4n/CQGV4F2bhdGVdxCTE/o38YqwQEp2KYUTnrHkZ72WLE1bRIdduh3lo=
